---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgdump
spec:
  backoffLimit: 0
  template:
    metadata:
      name: pgdump
      labels:
        app: pgdump
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-backup"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-backup"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-backup" -}}
          postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres.postgres.svc:5432/wizard
          {{- end }}
        vault.hashicorp.com/role: "db-backup"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/tls-secret: "tls-test-client"
        vault.hashicorp.com/client-cert: "/vault/tls/client.crt"
        vault.hashicorp.com/client-key: "/vault/tls/client.key"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
    spec:
      serviceAccountName: pgdump
      containers:
      - name: pgdump
        image: postgres:11.5
        command:
          - "/bin/sh"
          - "-ec"
        args:
          - "/usr/bin/pg_dump $(cat /vault/secrets/db-creds) --no-owner > /dev/stdout"
      restartPolicy: Never
