global:
  tlsDisable: false

injector:
  image:
    tag: "0.2.0"

server:
  extraVolumes:
  - type: secret
    name: demo-vault
  - type: secret
    name: tls-test-server
  - type: secret
    name: tls-test-client
  extraEnvironmentVar:
    VAULT_CACERT=/vault/userconfig/tls-test-server/ca.crt
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/tls-test-server/server.crt"
        tls_key_file = "/vault/userconfig/tls-test-server/server.key"
        tls_client_ca_file = "/vault/userconfig/tls-test-server/ca.crt"
      }
      storage "file" {
        path = "/vault/data"
      }
  readinessProbe:
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
