global:
  tlsDisable: true

server:
  image:
    repository: "vault"
    tag: "1.4.1"
  extraVolumes:
  - type: secret
    name: demo-vault
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = 1
      }
      storage "file" {
        path = "/vault/data"
      }
  readinessProbe:
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
